version: "3.8"

services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    command: mage start ml_pipeline
    ports:
      - "6789:6789"
    volumes:
      - ./ml_pipeline:/home/src
    environment:
      - USER_CODE_PATH=/home/src
